<?php 
  $page = 'home';
  $srplink = 'home';
?>


<!doctype html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><html lang="en" class="no-js"> <![endif]-->
<html lang="en">

<head>

  <!-- Basic -->
  <title>HOME | TRAFFIC SOLUTIONS EXPO</title>

  <!-- Define Charset -->
  <meta charset="utf-8">

  <!-- Responsive Metatag -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Page Description and Author -->
  <meta name="description" content="Welcome to the traffic fair in Serbia, TRAFFIC SOLUTIONS EXPO, Novi Sad, Serbia. Find out more!">
  <meta name="author" content="ASajfar">

  <link rel="icon" href="/favicon.ico" type="image/x-icon">

  <!-- Bootstrap CSS  -->
  <link rel="stylesheet" href="asset/css/bootstrap.min.css" type="text/css" media="screen">

  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="css/font-awesome.min.css" type="text/css" media="screen">

  <!-- Slicknav - responsive Mobile menu -->
  <link rel="stylesheet" type="text/css" href="css/slicknav.css" media="screen">

  <!-- Site CSS Styles  -->
  <link rel="stylesheet" type="text/css" href="css/style.css" media="screen">

  <!-- Responsive CSS Styles  -->
  <link rel="stylesheet" type="text/css" href="css/responsive.css" media="screen">

  <!-- Css3 Transitions Styles  -->
  <link rel="stylesheet" type="text/css" href="css/animate.css" media="screen">

  <!-- Color CSS Styles  -->
  <link rel="stylesheet" type="text/css" href="css/colors/red.css" title="red" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/jade.css" title="jade" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/green.css" title="green" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/blue.css" title="blue" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/beige.css" title="beige" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/cyan.css" title="cyan" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/orange.css" title="orange" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/peach.css" title="peach" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/pink.css" title="pink" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/purple.css" title="purple" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/sky-blue.css" title="sky-blue" media="screen" />
  <link rel="stylesheet" type="text/css" href="css/colors/yellow.css" title="yellow" media="screen" />

  <!-- Site JS  -->
  <script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
  <script type="text/javascript" src="js/jquery.migrate.js"></script>
  <script type="text/javascript" src="js/modernizrr.js"></script>
  <script type="text/javascript" src="asset/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="js/jquery.fitvids.js"></script>
  <script type="text/javascript" src="js/owl.carousel.min.js"></script>
  <script type="text/javascript" src="js/nivo-lightbox.min.js"></script>
  <script type="text/javascript" src="js/jquery.isotope.min.js"></script>
  <script type="text/javascript" src="js/jquery.appear.js"></script>
  <script type="text/javascript" src="js/count-to.js"></script>
  <script type="text/javascript" src="js/jquery.textillate.js"></script>
  <script type="text/javascript" src="js/jquery.lettering.js"></script>
  <script type="text/javascript" src="js/jquery.easypiechart.min.js"></script>
  <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
  <script type="text/javascript" src="js/jquery.parallax.js"></script>
  <script type="text/javascript" src="js/mediaelement-and-player.js"></script>
  <script type="text/javascript" src="js/jquery.slicknav.js"></script>
  

  <!--[if IE 8]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

  <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Event",
  "name": "TRAFFIC SOLUTIONS EXPO 2018",
  "description": "TRAFFIC SOLUTIONS EKSPO aims to contribute to the overall development of traffic, presenting various products and services, linking stakeholders and informing the professionals and the general public.",
  "image": "http://ts-expo.rs/en/images/tslogo2.png",
  "startDate": "2018-10-16T00:00",
  "endDate": "2018-09-18T00:00",
  "location": {
    "@type": "Place",
    "name": "Novi Sad Fair",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "Hajduk Veljkova 11",
      "addressLocality": "Novi Sad",
      "postalCode": "21000",
      "addressCountry": "RS"
    }
  }
}
</script>

  <!-- Google Analytics Code -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76465485-1', 'auto');
  ga('send', 'pageview');

  </script>

</head>

<body>

<!-- Popup window -->
<!-- <div class="pop-up">
    <div class="pop-box pop-small-6 large-centered">
      <h3>Dear friends, colleagues and associates,</h3>
      
      <p>Thank you on your cooperation, registration and willingness to actively participate in the implementation of Traffic Solutions Expo 2016.</p>
     <p> Unfortunately, due to the fact that such an event is planed for the first time in Serbia and that this was an election year in Serbia at all levels, every day we were faced with a lack of time for quality realization of this event. Because of that we were forced to make a decision to move the deadline of Traffic Solutions Expo on 2017.</p>
      <p>Bearing in mind that in the current preparations for the Traffic Solutions Expo all instances the authorities, professional and general public have shown willingness and interest in active involvement in the organization of the event, we invite you to continue our current cooperation and prepare for the next year.</p>
      <p>We believe that together with you, but also whit additional time that we have now, will succeed to organize an quality event and on satisfaction of all.</p>
      <p>More information about <strong>TRAFFIC SOLUTION EXPO 2017</strong> will soon be available on our site www.ts-expo.rs.</p>
      <p>For any additional questions or information, please do not hesitate to contact us.</p>
      <p>Thank you in advance for your understanding of the situation.</p>
      <p>TRAFFIC SOLUTIONS EXPO Team!</p>

    </div>
  </div> -->

  <!-- Full Body Container -->

  <!-- Tab sa strane ciji link vodi ka B2B stranici  -->

  <!-- <div id="side-tab">
      <a class="b2b" onmouseover="changeb2b(this)" onmouseout="normalb2b(this)" target="_blank" href="http://trafficb2b2017.talkb2b.net/"></a>
  </div> -->

  <!-- kraja taba  -->

  <div id="container">


    <!-- Start Header Section -->
    <?php 
      include 'header-en.php';
    ?>
    <!-- End Header Section -->


    <!-- Start Page Banner -->
    <div class="page-banner-naslovna">
      <!-- <div class="slika"></div> -->
      <div class="crossfade">
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
        <figure></figure>
      </div>
      <div class="slika-effect1"></div>
      <div class="slika-effect2"></div>
      <div class="row-slide">
        <div class="naslov1_sr">WELCOME TO</div>
        <div class="naslov2_sr">TRAFFIC SOLUTIONS EXPO</div>
        <div class="naslov3">16-18 OCTOBER 2018</div>
        <div>
          <a href="docs/reg/Registration_form_2018.pdf" target="_blank"><button class="register-button">Exhibitors registration form</button></a>
          <a href="docs/reg/General_terms_and_conditions_for_exhibiting-2018.pdf" target="_blank"><button class="register-button">Exhibiting terms and conditions</button></a>
          <button class="register-button" data-toggle="modal" data-target="#myModalHorizontal">Visitors registration form</button>
        </div>
      </div>
      <div class="tekst-box">
        <div class="tekst1 col-xs-12 col-md-4">
          <h1>ORGANIZERS</h1>
          <p>Public connection Ltd, Novi Sad</p>
          <p><a class="link-naslovna" href="http://www.sajam.net/live/Congress+Centre" target="_blank">Novi Sad Fair joint- stock company, Novi Sad</a></p>
          <p><a class="link-naslovna" href="http://www.navak.rs/" target="_blank">NAVAK - National Drivers Àcademy Ltd., Belgrade</a></p>
          <!-- <p><a class="link-naslovna" href="http://www.ftn.uns.ac.rs/1742896254/departman-za-saobracaj" target="_blank">Faculty of Technical Sciences - Traffic Department, University of Novi Sad</a></p> -->
          <!-- <p><a class="link-naslovna" href="http://www.sf.bg.ac.rs/index.php/en/" target="_blank">Faculty of Transport and Traffic Engineering, University of Belgrade</a></p>
          <p><a class="link-naslovna" href="http://een.ec.europa.eu/" target="_blank">Enterprise Europe Network</a></p> -->
        </div>
        <div class="tekst1 col-xs-12 col-md-4">
          <h1>SUPORTED BY</h1>
          <p><a class="link-naslovna" href="http://www.mgsi.gov.rs/" target="_blank">The Ministry of Construction, Transport/Traffic and Infrastructure of the Republic of Serbia</a></p>
           <p><a class="link-naslovna" href="http://www.psemr.vojvodina.gov.rs/" target="_blank">Autonomous Province of Vojvodina
          - Provincial Secretariat for Energy and Mineral Resources</a></p>
           <p><a class="link-naslovna" href="http://www.novisad.rs/eng" target="_blank">City of Novi Sad</a></p>
          <!-- <p><a class="link-naslovna" href="http://een.ec.europa.eu/" target="_blank">Enterprise Europe network</a></p> -->
          <p><a class="link-naslovna" href="http://www.buildplus.rs/" target="_blank">BUILD plus</a></p>
          <!-- <p><a class="link-naslovna" href="http://www.pks.rs/Default.aspx?idjezik=3" target="_blank">Chamber of Commerce and Industry of Serbia</a></p> -->
          <!-- <p><a class="link-naslovna" href="http://www.kombeg.org.rs/EIndex.aspx" target="_blank">Belgrade Chamber of Commerce</a></p> -->
          <!-- <p><a class="link-naslovna" href="http://www.rtv.rs/sr_lat/about-us/" target="_blank">The Public Broadcasting Service of Vojvodina, RTV</a></p> -->
        </div>
        <div class="tekst1 col-xs-12 col-md-4">
          <h1>DATE AND PLACE</h1>
          <p style="font-size: 1.1em; color: white;">16-18 october 2018</p>
          <p>Novi Sad Fair</p>
          <p>Hajduk Veljkova 11, 21000 Novi Sad, Serbia</p>
        </div>

      </div>      
      
    </div>

    <div class="logos">
      <div class="row">
        <div class="col-md-12" data-animation="fadeIn" data-animation-delay="01">
          <ul>
            <li><img style="cursor: pointer;" src="../en/images/logos/01-Public-Connection-doo-small-2.png" alt="logo" title="Public connection Ltd, Novi Sad"></li>
            <li><a href="http://www.sajam.net/live/?languageId=1" target="_blank"><img src="../en/images/logos/02-Sajam_logo_small-2.png" alt="logo" title="Novi Sad Fair"></a></li>
            <li><a href="http://www.navak.rs/" target="_blank"><img src="../en/images/logos/navakH_small-2.png" alt="logo" title="NAVAK - Nacionalna Vozačka Akademija"></a></li>
            <!-- <li><a href="http://www.ftn.uns.ac.rs/n1386094394/faculty-of-technical-sciences" target="_blank"><img src="../en/images/logos/03-FTN_Logo-small.png" alt="logo" title="Faculty of Technical Sciences, University of Novi Sad"></a></li> -->
            <!-- <li><a href="http://www.sf.bg.ac.rs/index.php/en/" target="_blank"><img src="../en/images/logos/04-SF-Beograd-small.png" alt="logo" title="Faculty of Transport and Traffic Engineering, University of Belgrade"></a></li> -->
            <!-- <li><a href="http://een.ec.europa.eu/" target="_blank"><img src="../en/images/logos/05-EEN-small.png" alt="logo" title="Enterprise Europe Network"></a></li> -->
            <li><a href="http://www.mgsi.gov.rs/lat" target="_blank"><img src="../en/images/logos/06-Ministarstvo_logo_small-2.png" alt="logo" title="The Ministry of Construction, Transport/Traffic and Infrastructure of the Republic of Serbia"></a></li>
            <li><a href="http://www.psemr.vojvodina.gov.rs/" target="_blank"><img src="../en/images/logos/07-APV-grb_small-2.png" alt="logo" title="Autonomous Province of Vojvodina - Provincial Secretariat for Energy and Mineral Resources"></a></li>
            <li><a href="http://www.novisad.rs/eng" target="_blank"><img src="../en/images/logos/08-Grad-Novi-Sad_small-2.png" alt="logo" title="City of Novi Sad"></a></li>
            <!-- <li><a href="http://www.pks.rs/Default.aspx?idjezik=3" target="_blank"><img src="../en/images/logos/09-PKS_1-small.png" alt="logo" title="Chamber of Commerce and Industry of Serbia"></a></li> -->
            <!-- <li><a href="http://www.kombeg.org.rs/EIndex.aspx" target="_blank"><img src="../en/images/logos/10-PKB_1-small.png" alt="logo" title="Belgrade Chamber of Commerce"></a></li> -->
            <!-- <li><a href="http://www.rtv.rs/sr_lat/about-us" target="_blank"><img src="../en/images/logos/11-RTV-small.png" alt="logo" title="The Public Broadcasting Service of Vojvodina, RTV"></a></li> -->
            <li><a href="http://www.buildplus.rs/" target="_blank"><img src="../en/images/logos/12-Build-plus_small-2.png" alt="logo" title="BUILD plus"></a></li>
            <!-- <li><a href="http://en.abs.gov.rs/" target="_blank"><img src="../en/images/logos/13-ABS-small.png" alt="logo" title="Road Traffic Safety Agency, Republic of Serbia"></a></li> -->         
          </ul>
        </div>        
      </div> 
    </div>

    <div class="container why">
      <div class="row">
        <div class="col-md-12" data-animation="fadeIn" data-animation-delay="01">
          <h4 class="classic-title" id="why">
            <span>WHY</span>
          </h4>
          <p>Every day our society faces increasing demands in terms of mobility and safety of participants, infrastructure construction, goods and passenger transport, environmental protection and better connections between different types of traffic.</p>
          <p>Following these challenges, TRAFFIC SOLUTIONS EKSPO aims to contribute to the overall development of traffic, presenting various products and services, linking stakeholders and informing the professionals and the general public.</p>
          <p>We expect more than 600 participants to visit TRAFFIC SOLUTIONS EXPO 2018 - professionals, decision makers in the field of transport and the wider public.</p>
        </div>
      </div>
    </div>

    <!--
    <div class="words-keys">
      <div class="col-md-12" data-animation="fadeIn" data-animation-delay="01">
        <div class="words-content">
        
             Traffic systems <span class="razdel">|</span> Traffic design <span class="razdel">|</span> Traffic Infrastructure <span class="razdel">|</span> Mechanization and equipment <span class="razdel">|</span> Traffic planning and Traffic Management <span class="razdel">|</span> Traffic Safety <span class="razdel">|</span> Traffic Signalization and equipment <span class="razdel">|</span> Transport and Logistics <span class="razdel">|</span> Urban Public Transport <span class="razdel">|</span> Urban Mobility <span class="razdel">|</span> Intelligent Transportation Systems (ITS) <span class="razdel">|</span> Accessibility <span class="razdel">|</span> Traffic Investments
        
        </div>          
      </div>
    </div>-->
    <!-- End Page Banner -->


    <div class="hr1" style="margin-bottom:50px;"></div>



  <!-- Start Footer -->
    <?php 
      include 'footer-en.php';
    ?>
  <!-- End Footer -->

  <!-- Go To Top Link -->
  <a href="#" class="back-to-top"><i class="fa fa-angle-up"></i></a>

  <div id="loader">
    <div class="spinner">
      <div class="dot1"></div>
      <div class="dot2"></div>
    </div>
  </div>

  <!-- Style Switcher 
  <div class="switcher-box">
    <a class="open-switcher show-switcher"><i class="fa fa-cog fa-2x"></i></a>
    <h4>Style Switcher</h4>
    <span>12 Predefined Color Skins</span>
    <ul class="colors-list">
      <li>
        <a onClick="setActiveStyleSheet('blue'); return false;" title="Blue" class="blue"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('sky-blue'); return false;" title="Sky Blue" class="sky-blue"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('cyan'); return false;" title="Cyan" class="cyan"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('jade'); return false;" title="Jade" class="jade"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('green'); return false;" title="Green" class="green"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('purple'); return false;" title="Purple" class="purple"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('pink'); return false;" title="Pink" class="pink"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('red'); return false;" title="Red" class="red"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('orange'); return false;" title="Orange" class="orange"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('yellow'); return false;" title="Yellow" class="yellow"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('peach'); return false;" title="Peach" class="peach"></a>
      </li>
      <li>
        <a onClick="setActiveStyleSheet('beige'); return false;" title="Biege" class="beige"></a>
      </li>
    </ul>
    <span>Top Bar Color</span>
    <select id="topbar-style" class="topbar-style">
      <option value="1">Light (Default)</option>
      <option value="2">Dark</option>
      <option value="3">Color</option>
    </select>
    <span>Layout Style</span>
    <select id="layout-style" class="layout-style">
      <option value="1">Wide</option>
      <option value="2">Boxed</option>
    </select>
    <span>Patterns for Boxed Version</span>
    <ul class="bg-list">
      <li>
        <a href="#" class="bg1"></a>
      </li>
      <li>
        <a href="#" class="bg2"></a>
      </li>
      <li>
        <a href="#" class="bg3"></a>
      </li>
      <li>
        <a href="#" class="bg4"></a>
      </li>
      <li>
        <a href="#" class="bg5"></a>
      </li>
      <li>
        <a href="#" class="bg6"></a>
      </li>
      <li>
        <a href="#" class="bg7"></a>
      </li>
      <li>
        <a href="#" class="bg8"></a>
      </li>
      <li>
        <a href="#" class="bg9"></a>
      </li>
      <li>
        <a href="#" class="bg10"></a>
      </li>
      <li>
        <a href="#" class="bg11"></a>
      </li>
      <li>
        <a href="#" class="bg12"></a>
      </li>
      <li>
        <a href="#" class="bg13"></a>
      </li>
      <li>
        <a href="#" class="bg14"></a>
      </li>
    </ul>
  </div>-->

  <script type="text/javascript" src="js/script.js"></script>

  <!-- JavaScript za popup window -->
  <!-- <script>
    
    $(function() {
      $('.pop-up').hide();
      $('.pop-up').fadeIn(700);
      $('#container').addClass('blur-in');
      
          $('.close-button').click(function (e) { 

          $('.pop-up').fadeOut(700);
          $('#container').removeClass('blur-in');
          $('#container').addClass('blur-out');
          e.stopPropagation();
            
        });
     });

  </script> -->

  <!-- Modal -->
  <div class="modal fade" id="myModalHorizontal" tabindex="-1" role="dialog" 
       aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <!-- Modal Header -->
              <div class="modal-header">
                  <button type="button" class="close" 
                     data-dismiss="modal">
                         <span aria-hidden="true">&times;</span>
                         <span class="sr-only">Close</span>
                  </button>
                  <h4 class="modal-title" id="myModalLabel">
                      Application form
                  </h4>
              </div>
              
              <!-- Modal Body -->
              <div class="modal-body">
                  
                  <form class="form-horizontal" role="form" action="php/registration.php" method="POST">
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="firstname">First name</label>
                      <div class="col-sm-10">
                          <input type="text" name="firstname" class="form-control" 
                          id="firstname" placeholder="First name" required/>
                      </div>
                    </div>
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="lastname">Last name</label>
                      <div class="col-sm-10">
                          <input type="text" name="lastname" class="form-control" 
                          id="lastname" placeholder="Last name" required/>
                      </div>
                    </div>
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="gender">Gender</label>
                      <div class="col-sm-10">
                        <label class="radio-inline" style="font-family: 'Roboto'; font-weight:300;"><input type="radio" name="gender" value="Male">Male</label>
                        <label class="radio-inline" style="font-family: 'Roboto'; font-weight:300;"><input type="radio" name="gender" value="Female">Female</label>
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="company">Company</label>
                      <div class="col-sm-10">
                          <input type="text" name="company" class="form-control" 
                          id="company" placeholder="Company"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="work-position">Work position</label>
                      <div class="col-sm-10">
                          <input type="text" name="work-position" class="form-control" 
                          id="work-position" placeholder="Work position"/>
                      </div>
                    </div>     
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="country">Country</label>
                      <div class="col-sm-10">
                          <select name="country" class="form-control" 
                          id="country" placeholder="Country" required/>
                            <option value="">Country...</option>
                            <option value="Afganistan">Afghanistan</option>
                            <option value="Albania">Albania</option>
                            <option value="Algeria">Algeria</option>
                            <option value="American Samoa">American Samoa</option>
                            <option value="Andorra">Andorra</option>
                            <option value="Angola">Angola</option>
                            <option value="Anguilla">Anguilla</option>
                            <option value="Antigua &amp; Barbuda">Antigua &amp; Barbuda</option>
                            <option value="Argentina">Argentina</option>
                            <option value="Armenia">Armenia</option>
                            <option value="Aruba">Aruba</option>
                            <option value="Australia">Australia</option>
                            <option value="Austria">Austria</option>
                            <option value="Azerbaijan">Azerbaijan</option>
                            <option value="Bahamas">Bahamas</option>
                            <option value="Bahrain">Bahrain</option>
                            <option value="Bangladesh">Bangladesh</option>
                            <option value="Barbados">Barbados</option>
                            <option value="Belarus">Belarus</option>
                            <option value="Belgium">Belgium</option>
                            <option value="Belize">Belize</option>
                            <option value="Benin">Benin</option>
                            <option value="Bermuda">Bermuda</option>
                            <option value="Bhutan">Bhutan</option>
                            <option value="Bolivia">Bolivia</option>
                            <option value="Bonaire">Bonaire</option>
                            <option value="Bosnia &amp; Herzegovina">Bosnia &amp; Herzegovina</option>
                            <option value="Botswana">Botswana</option>
                            <option value="Brazil">Brazil</option>
                            <option value="British Indian Ocean Ter">British Indian Ocean Ter</option>
                            <option value="Brunei">Brunei</option>
                            <option value="Bulgaria">Bulgaria</option>
                            <option value="Burkina Faso">Burkina Faso</option>
                            <option value="Burundi">Burundi</option>
                            <option value="Cambodia">Cambodia</option>
                            <option value="Cameroon">Cameroon</option>
                            <option value="Canada">Canada</option>
                            <option value="Canary Islands">Canary Islands</option>
                            <option value="Cape Verde">Cape Verde</option>
                            <option value="Cayman Islands">Cayman Islands</option>
                            <option value="Central African Republic">Central African Republic</option>
                            <option value="Chad">Chad</option>
                            <option value="Channel Islands">Channel Islands</option>
                            <option value="Chile">Chile</option>
                            <option value="China">China</option>
                            <option value="Christmas Island">Christmas Island</option>
                            <option value="Cocos Island">Cocos Island</option>
                            <option value="Colombia">Colombia</option>
                            <option value="Comoros">Comoros</option>
                            <option value="Congo">Congo</option>
                            <option value="Cook Islands">Cook Islands</option>
                            <option value="Costa Rica">Costa Rica</option>
                            <option value="Cote DIvoire">Cote D'Ivoire</option>
                            <option value="Croatia">Croatia</option>
                            <option value="Cuba">Cuba</option>
                            <option value="Curaco">Curacao</option>
                            <option value="Cyprus">Cyprus</option>
                            <option value="Czech Republic">Czech Republic</option>
                            <option value="Denmark">Denmark</option>
                            <option value="Djibouti">Djibouti</option>
                            <option value="Dominica">Dominica</option>
                            <option value="Dominican Republic">Dominican Republic</option>
                            <option value="East Timor">East Timor</option>
                            <option value="Ecuador">Ecuador</option>
                            <option value="Egypt">Egypt</option>
                            <option value="El Salvador">El Salvador</option>
                            <option value="Equatorial Guinea">Equatorial Guinea</option>
                            <option value="Eritrea">Eritrea</option>
                            <option value="Estonia">Estonia</option>
                            <option value="Ethiopia">Ethiopia</option>
                            <option value="Falkland Islands">Falkland Islands</option>
                            <option value="Faroe Islands">Faroe Islands</option>
                            <option value="Fiji">Fiji</option>
                            <option value="Finland">Finland</option>
                            <option value="France">France</option>
                            <option value="French Guiana">French Guiana</option>
                            <option value="French Polynesia">French Polynesia</option>
                            <option value="French Southern Ter">French Southern Ter</option>
                            <option value="Gabon">Gabon</option>
                            <option value="Gambia">Gambia</option>
                            <option value="Georgia">Georgia</option>
                            <option value="Germany">Germany</option>
                            <option value="Ghana">Ghana</option>
                            <option value="Gibraltar">Gibraltar</option>
                            <option value="Great Britain">Great Britain</option>
                            <option value="Greece">Greece</option>
                            <option value="Greenland">Greenland</option>
                            <option value="Grenada">Grenada</option>
                            <option value="Guadeloupe">Guadeloupe</option>
                            <option value="Guam">Guam</option>
                            <option value="Guatemala">Guatemala</option>
                            <option value="Guinea">Guinea</option>
                            <option value="Guyana">Guyana</option>
                            <option value="Haiti">Haiti</option>
                            <option value="Hawaii">Hawaii</option>
                            <option value="Honduras">Honduras</option>
                            <option value="Hong Kong">Hong Kong</option>
                            <option value="Hungary">Hungary</option>
                            <option value="Iceland">Iceland</option>
                            <option value="India">India</option>
                            <option value="Indonesia">Indonesia</option>
                            <option value="Iran">Iran</option>
                            <option value="Iraq">Iraq</option>
                            <option value="Ireland">Ireland</option>
                            <option value="Isle of Man">Isle of Man</option>
                            <option value="Israel">Israel</option>
                            <option value="Italy">Italy</option>
                            <option value="Jamaica">Jamaica</option>
                            <option value="Japan">Japan</option>
                            <option value="Jordan">Jordan</option>
                            <option value="Kazakhstan">Kazakhstan</option>
                            <option value="Kenya">Kenya</option>
                            <option value="Kiribati">Kiribati</option>
                            <option value="Korea North">Korea North</option>
                            <option value="Korea Sout">Korea South</option>
                            <option value="Kuwait">Kuwait</option>
                            <option value="Kyrgyzstan">Kyrgyzstan</option>
                            <option value="Laos">Laos</option>
                            <option value="Latvia">Latvia</option>
                            <option value="Lebanon">Lebanon</option>
                            <option value="Lesotho">Lesotho</option>
                            <option value="Liberia">Liberia</option>
                            <option value="Libya">Libya</option>
                            <option value="Liechtenstein">Liechtenstein</option>
                            <option value="Lithuania">Lithuania</option>
                            <option value="Luxembourg">Luxembourg</option>
                            <option value="Macau">Macau</option>
                            <option value="Macedonia">Macedonia</option>
                            <option value="Madagascar">Madagascar</option>
                            <option value="Malaysia">Malaysia</option>
                            <option value="Malawi">Malawi</option>
                            <option value="Maldives">Maldives</option>
                            <option value="Mali">Mali</option>
                            <option value="Malta">Malta</option>
                            <option value="Marshall Islands">Marshall Islands</option>
                            <option value="Martinique">Martinique</option>
                            <option value="Mauritania">Mauritania</option>
                            <option value="Mauritius">Mauritius</option>
                            <option value="Mayotte">Mayotte</option>
                            <option value="Mexico">Mexico</option>
                            <option value="Midway Islands">Midway Islands</option>
                            <option value="Moldova">Moldova</option>
                            <option value="Monaco">Monaco</option>
                            <option value="Mongolia">Mongolia</option>
                            <option value="Montserrat">Montserrat</option>
                            <option value="Morocco">Morocco</option>
                            <option value="Mozambique">Mozambique</option>
                            <option value="Myanmar">Myanmar</option>
                            <option value="Nambia">Nambia</option>
                            <option value="Nauru">Nauru</option>
                            <option value="Nepal">Nepal</option>
                            <option value="Netherland Antilles">Netherland Antilles</option>
                            <option value="Netherlands">Netherlands (Holland, Europe)</option>
                            <option value="Nevis">Nevis</option>
                            <option value="New Caledonia">New Caledonia</option>
                            <option value="New Zealand">New Zealand</option>
                            <option value="Nicaragua">Nicaragua</option>
                            <option value="Niger">Niger</option>
                            <option value="Nigeria">Nigeria</option>
                            <option value="Niue">Niue</option>
                            <option value="Norfolk Island">Norfolk Island</option>
                            <option value="Norway">Norway</option>
                            <option value="Oman">Oman</option>
                            <option value="Pakistan">Pakistan</option>
                            <option value="Palau Island">Palau Island</option>
                            <option value="Palestine">Palestine</option>
                            <option value="Panama">Panama</option>
                            <option value="Papua New Guinea">Papua New Guinea</option>
                            <option value="Paraguay">Paraguay</option>
                            <option value="Peru">Peru</option>
                            <option value="Phillipines">Philippines</option>
                            <option value="Pitcairn Island">Pitcairn Island</option>
                            <option value="Poland">Poland</option>
                            <option value="Portugal">Portugal</option>
                            <option value="Puerto Rico">Puerto Rico</option>
                            <option value="Qatar">Qatar</option>
                            <option value="Republic of Montenegro">Republic of Montenegro</option>
                            <option value="Republic of Serbia">Republic of Serbia</option>
                            <option value="Reunion">Reunion</option>
                            <option value="Romania">Romania</option>
                            <option value="Russia">Russia</option>
                            <option value="Rwanda">Rwanda</option>
                            <option value="St Barthelemy">St Barthelemy</option>
                            <option value="St Eustatius">St Eustatius</option>
                            <option value="St Helena">St Helena</option>
                            <option value="St Kitts-Nevis">St Kitts-Nevis</option>
                            <option value="St Lucia">St Lucia</option>
                            <option value="St Maarten">St Maarten</option>
                            <option value="St Pierre &amp; Miquelon">St Pierre &amp; Miquelon</option>
                            <option value="St Vincent &amp; Grenadines">St Vincent &amp; Grenadines</option>
                            <option value="Saipan">Saipan</option>
                            <option value="Samoa">Samoa</option>
                            <option value="Samoa American">Samoa American</option>
                            <option value="San Marino">San Marino</option>
                            <option value="Sao Tome &amp; Principe">Sao Tome &amp; Principe</option>
                            <option value="Saudi Arabia">Saudi Arabia</option>
                            <option value="Senegal">Senegal</option>
                            <option value="Serbia">Serbia</option>
                            <option value="Seychelles">Seychelles</option>
                            <option value="Sierra Leone">Sierra Leone</option>
                            <option value="Singapore">Singapore</option>
                            <option value="Slovakia">Slovakia</option>
                            <option value="Slovenia">Slovenia</option>
                            <option value="Solomon Islands">Solomon Islands</option>
                            <option value="Somalia">Somalia</option>
                            <option value="South Africa">South Africa</option>
                            <option value="Spain">Spain</option>
                            <option value="Sri Lanka">Sri Lanka</option>
                            <option value="Sudan">Sudan</option>
                            <option value="Suriname">Suriname</option>
                            <option value="Swaziland">Swaziland</option>
                            <option value="Sweden">Sweden</option>
                            <option value="Switzerland">Switzerland</option>
                            <option value="Syria">Syria</option>
                            <option value="Tahiti">Tahiti</option>
                            <option value="Taiwan">Taiwan</option>
                            <option value="Tajikistan">Tajikistan</option>
                            <option value="Tanzania">Tanzania</option>
                            <option value="Thailand">Thailand</option>
                            <option value="Togo">Togo</option>
                            <option value="Tokelau">Tokelau</option>
                            <option value="Tonga">Tonga</option>
                            <option value="Trinidad &amp; Tobago">Trinidad &amp; Tobago</option>
                            <option value="Tunisia">Tunisia</option>
                            <option value="Turkey">Turkey</option>
                            <option value="Turkmenistan">Turkmenistan</option>
                            <option value="Turks &amp; Caicos Is">Turks &amp; Caicos Is</option>
                            <option value="Tuvalu">Tuvalu</option>
                            <option value="Uganda">Uganda</option>
                            <option value="Ukraine">Ukraine</option>
                            <option value="United Arab Erimates">United Arab Emirates</option>
                            <option value="United Kingdom">United Kingdom</option>
                            <option value="United States of America">United States of America</option>
                            <option value="Uraguay">Uruguay</option>
                            <option value="Uzbekistan">Uzbekistan</option>
                            <option value="Vanuatu">Vanuatu</option>
                            <option value="Vatican City State">Vatican City State</option>
                            <option value="Venezuela">Venezuela</option>
                            <option value="Vietnam">Vietnam</option>
                            <option value="Virgin Islands (Brit)">Virgin Islands (Brit)</option>
                            <option value="Virgin Islands (USA)">Virgin Islands (USA)</option>
                            <option value="Wake Island">Wake Island</option>
                            <option value="Wallis &amp; Futana Is">Wallis &amp; Futana Is</option>
                            <option value="Yemen">Yemen</option>
                            <option value="Zaire">Zaire</option>
                            <option value="Zambia">Zambia</option>
                            <option value="Zimbabwe">Zimbabwe</option>
                          </select>  
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="city">City</label>
                      <div class="col-sm-10">
                          <input type="text" name="city" class="form-control" 
                          id="city" placeholder="City"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="phone">Phone number</label>
                      <div class="col-sm-10">
                          <input type="text" name="phone" class="form-control" 
                          id="phone" placeholder="Phone number"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="web-site">Web site</label>
                      <div class="col-sm-10">
                          <input type="text" name="web-site" class="form-control" 
                          id="web-site" placeholder="Web site"/>
                      </div>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="status">You are...</label>
                      <div class="col-sm-10">
                          <select name="status" class="form-control" id="status" placeholder="Status">
                            <option value="">You are...</option>
                            <option value="Visitor">Visitor</option>
                            <option value="Exhibitor">Exhibitor</option>
                            <option value="Press">Press</option>
                            <option value="Conference participant">Conference participant</option>
                          </select>  
                      </div>
                    </div>
                    <div>
                      <hr>
                    </div>  
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="username">User name</label>
                      <div class="col-sm-10">
                          <input type="text" name="username" class="form-control" 
                          id="username" placeholder="User name" required/>
                      </div>
                    </div>    
                    <div class="form-group required">
                      <label  class="col-sm-2 control-label"
                                for="email">Email</label>
                      <div class="col-sm-10">
                          <input type="email" name="email" class="form-control" 
                          id="email" placeholder="Email" required/>
                      </div>
                    </div>
                    <div class="form-group required">
                      <label  id="email2" class="col-sm-2 control-label"
                                for="email2">Email</label>
                      <div class="col-sm-10">
                          <input type="email" name="email2" class="form-control" 
                          id="email2" placeholder="Email address"/>
                      </div>
                    </div>
                    <div class="form-group required">
                      <label class="col-sm-2 control-label"
                            for="password">Password</label>
                      <div class="col-sm-10">
                          <input type="password" name="password" class="form-control"
                              id="password" placeholder="Password" required/>
                      </div>
                    </div>
                    <div>
                      <hr>
                    </div>
                    <div class="form-group">
                      <label  class="col-sm-2 control-label"
                                for="question">Question</label>
                      <div class="col-sm-10">
                          <textarea name="question" class="form-control" 
                          id="question" placeholder="Question..."></textarea>
                      </div>
                    </div>  
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" name="submit" class="btn btn-default">Sign in</button>
                      </div>
                    </div>
                  </form>                 
              </div>
              
              <!-- Modal Footer -->
              <div class="modal-footer">
                  <button type="button" class="btn btn-default"
                          data-dismiss="modal">
                              Close
                  </button>
              </div>
          </div>
      </div>
  </div>

  <!-- Skripta za onesposobljavanje linkova na stranici -->
  <!-- <script type="text/javascript">
    $(document).ready(function(){
      $("a").css("cursor","arrow").click(false);
      
      $(":input").prop("disabled",true);
    });
  </script> -->


</body>

<!-- javascript za prikaz taba sa strane - mouseover povecava sirinu, a mouseout vraca sirinu na prvobitnu dimenziju-->
<!-- <script>
  function changeb2b(x) {
    x.style.width = "560px";
  }

  function normalb2b(x) {
    x.style.width = "70px";
  }
</script> -->

</html>